import type {Metadata} from "next";
import '../styles/index.scss';
import {getMainMenu} from "@/services/Settings";
import AppShell from "@/theme/layouts/AppShell";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
  const menu = await getMainMenu();

  return (
    <html lang="en">
    <body>
    <AppShell menu={menu}>
      {children}
    </AppShell>
    </body>
    </html>
  );
}
