-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "finalPrice" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "price" DECIMAL(10,2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Variant" ADD COLUMN     "finalPrice" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "price" DECIMAL(10,2) NOT NULL DEFAULT 0,
ALTER COLUMN "title" DROP NOT NULL;
